# Generated by Django 4.2.8 on 2023-12-22 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("A", "0002_nothing"),
    ]

    operations = []
