# Generated by Django 4.2.8 on 2023-12-22 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("A", "0003_nothing"),
    ]

    operations = []
