# Generated by Django 4.2.8 on 2023-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("A", "0005_nothing"),
    ]

    operations = [
        migrations.AddField(
            model_name="a",
            name="new_field",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
