# Generated by Django 4.2.8 on 2023-12-22 20:59

from django.db import migrations


def migrate(apps, schema_editor):
    A = apps.get_model("A", "A")
    A.objects.all().update(new_field="buz")


class Migration(migrations.Migration):
    dependencies = [
        ("A", "0006_a_new_field"),
    ]

    operations = [migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop)]
