# Generated by Django 4.2.8 on 2023-12-22 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("B", "0001_nothing"),
    ]

    operations = []
