# Generated by Django 4.2.8 on 2023-12-22 18:52

from django.db import migrations


def migrate(apps, schema_editor):
    A = apps.get_model("A", "A")
    A.objects.all().update(a_field="bar")


class Migration(migrations.Migration):
    dependencies = [
        ("B", "0004_nothing"),
    ]

    operations = [migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop)]
